spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_food_guide?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
      username: root
      password: '010203'
  redis:
    host: 47.109.139.173
    port: 6379
    database: 5
    timeout: 1800000
    password: '010203'