spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_food_guide?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
      username: root
      password: '010203'
  redis:
    host: 47.109.139.173
    port: 6379
    database: 0
    timeout: 1800000
    password: '010203'
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.qq.com #邮件服务器地址
    port: 465 #端口号
    username: 210398042@qq.com
    password: lbbctyyvqnwobjje
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        debug: true #启动debug调试
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
minio:
  endpoint: http://47.109.139.173:9000
  access-key: paJorTMGQnUHTlZ5PWJ1
  secre-key: gwDjy61ZhVEQI7z2IOLu9q2dIAaw4ujifoUrCNSM
  bucketName: food.guide
