server:
  port: 8080

spring:
  profiles:
    active: dev
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
    #开启驼峰命名
    map-underscore-to-camel-case: true