server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: hcm
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
    #开启驼峰命名
    map-underscore-to-camel-case: true

# 将sql打印到控制台上
logging:
  level:
    com.zzmr.fgback.mapper: debug

fg:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: adminZZMRsdaf23ksfdkal
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置jwt加密时的密钥
    user-secret-key: userZZMR43dfasfdayadferdadgf
    # 设置jwt的过期时间
    user-ttl: 7200000
    # 设置前端传来的令牌名称
    user-token-name: token
  wechat:
    appid: wx26b00f9454de88a6
    secret: 6c4ad5db6efb880425969b7afe4099c7